apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: desafio-app
  name: desafio-app
spec:
  type: NodePort
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: desafio-app
status:
  loadBalancer: {}